# Generated by Django 5.2.15 on 2026-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contact', 'Contact message'), ('checklist', 'UAD 3.6 checklist request')], default='contact', max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
