# Generated by Django 5.2.16 on 2026-07-14 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreflightReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject_identifier', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preflight_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=80)),
                ('signature', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fix_before_delivery', 'Fix Before Delivery'), ('judgment_review', 'Judgment Review'), ('cleanup', 'Cleanup')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('advisory', 'Advisory')], max_length=20)),
                ('observed', models.TextField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('why_it_matters', models.TextField()),
                ('recommended_action', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('guidance', models.JSONField(default=list)),
                ('basis', models.CharField(default='deterministic', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='preflight.preflightreview')),
            ],
            options={
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('accepted_risk', 'Accepted Risk')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='preflight.reviewfinding')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('parsed', 'Parsed'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('package_hash', models.CharField(blank=True, max_length=64)),
                ('parser_version', models.CharField(default='preflight-1', max_length=30)),
                ('rule_version', models.CharField(default='rules-1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='preflight.preflightreview')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='reviewfinding',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='preflight.reviewversion'),
        ),
        migrations.CreateModel(
            name='ReviewFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='preflight/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('xml', 'XML'), ('pdf', 'PDF'), ('image', 'IMAGE'), ('ssr', 'SSR'), ('other', 'OTHER')], default='other', max_length=20)),
                ('sha256', models.CharField(max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='preflight.reviewversion')),
            ],
        ),
        migrations.CreateModel(
            name='WorkfileReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workfile_record', to='preflight.preflightreview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reviewversion',
            constraint=models.UniqueConstraint(fields=('review', 'number'), name='unique_preflight_version'),
        ),
    ]
