# Generated by Django 5.2.16 on 2026-07-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preflight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('normalized_value', models.CharField(blank=True, max_length=255)),
                ('source_kind', models.CharField(choices=[('xml', 'XML'), ('pdf', 'PDF'), ('image', 'IMAGE'), ('ssr', 'SSR'), ('other', 'OTHER')], max_length=20)),
                ('source_location', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='preflight.reviewfile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='preflight.reviewversion')),
            ],
        ),
    ]
