# Generated by Django 5.2.16 on 2026-07-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preflight', '0002_extractedobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=80)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='preflight-ai-1', max_length=30)),
                ('system_prompt', models.TextField(blank=True)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_response', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_executions', to='preflight.reviewversion')),
            ],
        ),
    ]
